### PR TITLE
SS-7391: Close popup on alert close

### PR DESCRIPTION
**Pull request by LemToUp**
https://shapediver.atlassian.net/browse/SS-7391

### CODE REVIEW

**Review by snabela — APPROVED** [review]
Thank you @LemToUp

**Review by snabela — CHANGES_REQUESTED** [review]
@LemToUp I reviewed this, and I think it's better if we don't show an alert popup window in case there is an exception. Instead, please show "Error while creating QR code" instead of the QR code, and log the exception to the browser console.

**Comment by LemToUp** [comment]
> @LemToUp I reviewed this, and I think it's better if we don't show an alert popup window in case there is an exception. Instead, please show "Error while creating QR code" instead of the QR code, and log the exception to the browser console.

@snabela done.

**Review by snabela — APPROVED** [review]
Many thanks @LemToUp !

**Pull request merged**
